import 'package:quitter/quitty/companion_mood.dart';

class StoryChapter {
  const StoryChapter(this.day, this.title, this.text);
  final int day;
  final String title;
  final String text;
}

/// Alle vier Figuren haben 9 Kapitel: Tag 1, 3, 7, 14, 30, 60, 90, 180, 365.
/// Tokens: {N} eigener Name, {G} Gitty, {P} Pjotre/Mica, {R} Rocco/Rocca, {D} Dieter/Dieta,
/// {er}/{Er}, {ihm}/{ihn}, {sein}, {Kleiner}. Die Wahl gilt für die ganze Gruppe.
const companionStories = <String, List<StoryChapter>>{
  'gitty': [
    StoryChapter(1, 'Die Kette', '{N} wacht auf, als der Regen schon durch die Gasse läuft. Der Mund schmeckt nach gestern. Etwas zieht am Knöchel: eine rostige Kette, jedes Glied so schwer wie eine Entscheidung, die {er} nie getroffen hat. {Er} erinnert sich nicht, wann sie dort angefangen hat, nur dass sie jede Nacht ein Stück gewachsen ist. Neben dem Müllcontainer liegt etwas Rotes. Ein Bolzenschneider, halb im Pfützenwasser. {N} starrt ihn lange an. Dann nimmt {er} ihn in die Hand. Er ist zu schwer, und genau das fühlt sich zum ersten Mal richtig an. Heute bricht {er} kein Glied. Heute steht {er} nur auf.'),
    StoryChapter(3, 'Das Zittern', 'Die Nächte sind laut geworden. Jedes Geräusch klingt nach dem, was {er} vermisst. {N} sitzt unter der Treppe und zittert, und das Zittern erzählt Geschichten: Nur einmal noch, dann hört es auf. {Er} hält den Bolzenschneider fest und sagt sich den Satz, den {er} sich vor drei Tagen ausgedacht hat. Der Drang kommt wie ein Zug durch einen Tunnel, laut, grell und viel zu nah. Aber Züge fahren weiter. Als der Lärm verklingt, ist es still, und {N} merkt, dass {er} noch da ist.'),
    StoryChapter(7, 'Das erste Glied', 'Es knackt. Kein Heldenmoment, nur ein kurzes Geräusch, als der Stahl in das rostige Metall beißt. Das erste Kettenglied fällt in die Pfütze und bleibt liegen. {N} sieht es an, als wäre es etwas Fremdes. Eine Woche, denkt {er}. Das klingt nach nichts und fühlt sich nach allem an. Am liebsten würde {er} es jemandem erzählen, aber wem? Über {ihm} auf dem Dach hat sich etwas bewegt. {N} schaut hoch und winkt vorsichtig.'),
    StoryChapter(14, '{D}, die Taube', '{D} ist eine Taube, die schon zu viel gesehen hat. Ein Flügel fehlt zur Hälfte, die Augen sind müde, aber freundlich. {D} sagt nicht viel, sitzt nur neben {N} und lässt {ihn} reden. Als {N} fertig ist, brummt {D}: Du musst das nicht allein machen, {Kleiner}. Hilfe annehmen ist keine Schwäche, sondern Handwerk. Ein Stück Brot rutscht über die Dachkante. Zwei Wochen, und zum ersten Mal sitzt {N} nicht allein in der Dunkelheit.'),
    StoryChapter(30, 'Der Markt der alten Gewohnheiten', '{N} hat den Weg lange gemieden. Heute geht {er} ihn doch, ganz bewusst, mit {D} im Rücken. Der Markt riecht nach allem, was {ihn} früher gehalten hat. Die Stände flüstern, die Lichter blinzeln, jemand ruft {sein} Namen. {N} bleibt stehen. Das Herz klopft laut. {Er} atmet vier Sekunden ein, sechs Sekunden aus. Dann dreht {er} sich um und geht. Nicht weil es leicht ist, sondern weil {er} jetzt weiß, wohin {er} will. Dreißig Tage, ein Monat, und das Echo des Marktes wird leiser.'),
    StoryChapter(60, 'Der Rückschlag', 'Es war kein großer Fehler, aber er fühlt sich riesig an. {N} sitzt in einer Pfütze aus Scham, der Bolzenschneider liegt daneben. Ich bin wieder am Anfang, flüstert {er}. {D} schüttelt langsam den Kopf. Nein, sagt {D}. Du bist an Tag sechzig plus einem schlechten Tag. Die Glieder, die du gebrochen hast, bleiben gebrochen. {N} weint ein bisschen, dann lacht {er} ein bisschen. Dann steht {er} auf. Nicht, weil {er} stark ist, sondern weil {er} keinen anderen Weg mehr kennt, der sich nach {ihm} anfühlt.'),
    StoryChapter(90, '{P}s Angebot', '{P} lehnt an der Mauer, die Mütze tief im Gesicht, und lächelt, als würde {er} ein Geheimnis kennen, das {N} noch nicht gehört hat. Ich hätte da etwas für dich, sagt {P}, ein einfacher Weg, ohne Mühe. {N} spürt das alte Ziehen. Aber {er} sieht auf die Hände, auf den Bolzenschneider, auf die Kettenglieder, die hinter {ihm} liegen wie eine Spur. Nein danke, sagt {N}. {P} zieht eine Augenbraue hoch, dann grinst {er}. Gut, sagt {P}. Das war die Prüfung. Neunzig Tage. Von jetzt an geht ihr zu zweit.'),
    StoryChapter(180, '{R} und die Brücke', '{R} trägt eine Maske und einen Plan. Am Fluss fehlt eine Brücke, und viele, die auf der anderen Seite leben, kommen nicht herüber. Wir bauen eine, sagt {R}. {N} zögert. {Er} hat selbst kaum festen Boden unter den Füßen. Aber {R} reicht {ihm} einen Hammer. Du hast den Weg gesehen, sagt {R}. Das macht dich zum Baumeister. Sie arbeiten drei Wochen lang. Jedes Brett ist ein Tag, jeder Nagel ein kleiner Sieg. Als die Brücke steht, geht das erste Kaninchen hinüber und sieht {N} an, als wäre {er} ein Vorbild.'),
    StoryChapter(365, 'Ohne Kette', 'Das letzte Glied ist dünn geworden, fast von allein. {N} setzt den Bolzenschneider an, und es knackt leise. Die Kette fällt in den Staub. {Er} steht lange da und merkt gar nicht, dass {er} weint. Ein Jahr. {D}, {P} und {R} stehen daneben und sagen nichts, weil es nichts zu sagen gibt. {N} hebt den Bolzenschneider auf und hängt ihn an die Wand der Werkstatt, die {er} gebaut hat. Draußen vor der Tür warten schon neue Gesichter mit schweren Ketten. {N} lächelt, öffnet die Tür und fragt: Willst du reinkommen? Ich weiß, wie es sich anfühlt.'),
  ],
  'pjotre': [
    StoryChapter(1, 'Rauch und Spiegel', '{N} lehnt am Laternenpfahl und ist mehr Schatten als Fuchs. Niemand weiß, woher {er} kommt, und das gefällt {ihm}. Rauch war immer {sein} Vorhang: Dahinter konnte {er} sein, wer {er} wollte. Heute zieht {er} zum ersten Mal die Mütze ab und sieht {sein} Spiegelbild in einer Pfütze. Da steht jemand, der müde ist. {N} blinzelt. Zum ersten Mal fragt {er} sich, was hinter dem Vorhang eigentlich auf {ihn} wartet.'),
    StoryChapter(3, 'Der Schatten im Fenster', 'Drei Tage, und {N} sieht {sein} Schatten im Fenster. Er wirkt kleiner als früher, aber schärfer. {Er} hebt die Hand, der Schatten tut es auch. Zum ersten Mal fühlt sich das nicht wie eine Drohung an, sondern wie eine Verabredung. Ich bin noch da, sagt {N} leise. Die Zukunft ist nichts als noch ein Tag, den {er} sich zutraut.'),
    StoryChapter(7, 'Die erste klare Nacht', 'Sieben Tage. {N} hat gelernt, dass Stille nicht leer ist. In den Nächten ohne Rauch hört {er} Dinge: Regen, Schritte, {sein} eigenes Herz. Es ist laut und ehrlich. {N} sitzt auf einem Dach und schaut auf die Stadt. Früher hat {er} sie nur durch einen Schleier gesehen. Jetzt hat sie Kanten und Farben. Nicht alles davon ist schön, aber es ist echt, und das genügt für den Moment.'),
    StoryChapter(14, 'Das Streichholz', 'Zwei Wochen. In der Manteltasche liegt noch immer ein Streichholzbriefchen. {N} dreht es in den Fingern. Früher war es ein Versprechen, heute ist es ein Beweis. Ich habe es nicht gebraucht, sagt {er}. Dann schnippt {er} es in die Regentonne. Das Zischen klingt wie ein kleiner Applaus.'),
    StoryChapter(30, 'Die Maske', 'Ein Monat. Auf dem Markt erkennt {N} niemand mehr, denn {er} ist ein bisschen anders. {Er} lächelt, wenn {er} lächeln will, und schweigt, wenn {er} schweigen will, nicht mehr aus Gewohnheit. Eine alte Händlerin sagt: Du siehst anders aus. {N} zuckt mit den Schultern. Besser, sagt {er}. Dann verschwindet {er} in der Menge, aber diesmal nicht, um sich zu verstecken.'),
    StoryChapter(60, 'Das Gewicht der Geheimnisse', 'Zwei Monate. Ein schlechter Tag zieht herauf, und {N} will alles für sich behalten wie früher. Aber {er} geht zu {G} und sagt: Ich brauche heute jemanden. Der Satz ist schwerer als jeder Rauch. {G} nickt nur und rückt ein Stück zur Seite. Zum ersten Mal teilt {N} ein Geheimnis, und es wird leichter.'),
    StoryChapter(90, '{G}s Prüfung', 'Neunzig Tage, und {N} hat etwas vor. Eine kleine Ratte soll getestet werden. Nicht aus Bosheit, sondern weil {N} weiß, wie leicht ein Ja ist. {Er} lehnt an der Mauer und bietet den einfachen Weg an. {G} sagt Nein, und {N} spürt etwas, das {er} lange nicht gespürt hat: Stolz auf jemand anderen. {Er} grinst und sagt: Gut, dann gehen wir zu zweit weiter. Geheimnisse sind schwer allein.'),
    StoryChapter(180, 'Die Karte ohne Namen', '{N} zeichnet eine Karte. Keine Schatzkarte, sondern eine Karte der Orte, an denen {er} früher schwach geworden ist, mit Wegen daran vorbei. Andere bekommen Kopien, ohne Namen und ohne Fragen. Sie liegen im Park, an Haltestellen und in Briefkästen. Ein halbes Jahr, und {N} hat verstanden, dass Geheimnis auch Schutz sein kann, wenn man ihn für andere einsetzt.'),
    StoryChapter(365, 'Der Mantel liegt offen', 'Ein Jahr. {N} steht auf dem Dach, auf dem alles anfing, und lässt den Mantel offen. Der Wind fährt hinein, und {er} lacht. Unten stehen {G}, {R} und {D} und winken. {N} wirft die Mütze hinunter, und jemand fängt sie auf. Ich hatte immer Geheimnisse, ruft {er}. Jetzt habe ich Freunde. Das ist besser. Hinter {ihm} geht die Sonne auf, und {er} dreht sich nicht mehr um.'),
  ],
  'rocco': [
    StoryChapter(1, 'Die Taschen voll Nichts', '{N} ist ein Meister im Sammeln. Knöpfe, Münzen, Schlüssel zu Türen, die es nicht mehr gibt. Die Taschen sind schwer, aber das Herz ist leer. Heute kippt {er} alles auf den Boden und sieht, was übrig bleibt: ein Haufen Zeug, das nichts füllt. {N} setzt sich dazwischen. Wenn {er} nicht sammelt, wer ist {er} dann? Die Frage ist neu und ein bisschen beängstigend. {Er} lässt sie stehen.'),
    StoryChapter(3, 'Der Hunger', 'Drei Tage. {N} ist unruhig. Die Finger suchen, die Augen wandern, der Magen knurrt, aber es ist kein Hunger nach Essen. Es ist ein Hunger nach Ablenkung. {Er} räumt die Hütte auf, sortiert Schrauben und zählt sie zweimal. Das hilft ein bisschen. Als es dunkel wird, atmet {er} aus. Heute hat {er} nichts mitgenommen. Und es fehlt nichts.'),
    StoryChapter(7, 'Leere Hände', 'Eine Woche. {N} weiß nicht, wohin mit den Händen. Früher haben sie immer etwas gehalten, jetzt hängen sie herunter. {Er} knetet sie, versteckt sie in den Ärmeln und schaut sie ratlos an. Eine alte Katze sagt: Hände sind nicht zum Festhalten da, sondern zum Anpacken. {N} bleibt skeptisch, aber am Abend repariert {er} einen kaputten Stuhl. Das Gefühl dabei ist neu, und {er} wiederholt es morgen.'),
    StoryChapter(14, 'Die Nacht der offenen Taschen', 'Zwei Wochen. {N} schläft zum ersten Mal ohne Taschen unter dem Kopfkissen. Früher hätte {er} jede Nacht kontrolliert, ob noch alles da ist. Heute liegt nichts darin. Die Hütte ist ruhig. Draußen fällt Regen aufs Dach, und {N} schläft ein, bevor {er} zu Ende gezählt hat.'),
    StoryChapter(30, 'Der Preis des Habens', 'Ein Monat, und {N} hat gelernt zu rechnen. Nicht in Münzen, sondern in Stunden, in Nächten, in Gesichtern, die {er} verpasst hat. Die Rechnung ist lang und bitter. Aber am Ende steht auch etwas Gutes: dreißig Tage, in denen {er} nichts genommen hat und trotzdem satt ist. {N} streicht über den Rand der Maske und lächelt. Das ist der beste Fund seit langer Zeit.'),
    StoryChapter(60, 'Der verlorene Knopf', 'Zwei Monate. Auf dem Markt blitzt ein glänzender Knopf, und {N} spürt das alte Ziehen. {Er} steht vor dem Stand und starrt. Dann fragt {er} die Verkäuferin, was er kostet. Sie lacht und schenkt ihn {ihm}. Der Knopf ist hübsch, aber nicht mehr als das. {N} steckt ihn ein und geht, ohne sich umzudrehen. Das ist neu.'),
    StoryChapter(90, '{G} braucht einen Schlafplatz', 'Draußen regnet es, und ein kleiner Rattenkopf schaut aus der Gasse. {N} zögert keine Sekunde. In der Hütte ist Platz, und es gibt heißen Tee. Früher hätte {er} {G} höchstens die Taschen geleert. Jetzt teilt {er} die Decke. Drei Monate. {N} hat entdeckt, dass Geben schwerer fällt als Nehmen und mehr bringt. Sie sitzen nebeneinander und schweigen, und es fühlt sich an wie Zuhause.'),
    StoryChapter(180, 'Die Brücke', '{N} hat einen Plan und viele Bretter. Über den Fluss soll eine Brücke, damit niemand mehr den langen Weg gehen muss. {Er} fragt alle, die {er} kennt, und fast alle sagen ja. {G} hält die Nägel, {D} den Zollstock. Ein halbes Jahr, und die Hände, die einmal nur sammelten, bauen etwas für alle. Als das letzte Brett sitzt, geht ein kleines Kaninchen als Erstes hinüber.'),
    StoryChapter(365, 'Reich', 'Ein Jahr. {N} hat noch immer Taschen, aber die sind leer, bis auf einen Schlüssel. Er passt zur Hütte, in der jeder schlafen darf. {Er} steht auf der Brücke und schaut auf das Wasser. Früher habe ich alles gewollt, denkt {er}. Heute weiß ich, was ich brauche. {N} lächelt, steckt die Hände in die Taschen und geht nach Hause, wo jemand auf {ihn} wartet.'),
  ],
  'dieter': [
    StoryChapter(1, 'Der Briefbote', '{N} war einmal Bote. Jahrelang flog {er} Nachrichten durch die Stadt, gute und schlechte, und trug sie alle allein. Irgendwann hat {er} angefangen, sich zu betäuben, damit nichts mehr zu schwer wurde. Heute sitzt {er} auf dem Dach und hat keine Post mehr. Nur den Himmel. Der Flügel schmerzt, die Augen sind müde, aber {N} atmet tief ein. Das Erste, was {er} sich zu sagen traut, ist: Genug.'),
    StoryChapter(3, 'Ohne Betäubung', 'Drei Tage. {N} spürt wieder alles: die Kälte der Dachziegel, den Hunger, das Ziehen im Flügel. Die Nachrichten von früher kommen als Bilder zurück, nicht alle gut. {Er} presst die Augen zu und wartet. Wenn etwas kommt, soll es kommen, denkt {er}, und wenn es vorbeigeht, auch. Als die Sonne aufgeht, ist {N} noch da.'),
    StoryChapter(7, 'Der Flügel', 'Sieben Tage. {N} untersucht den kaputten Flügel. Er wird nie wieder wie früher fliegen, das weiß {er}. Aber ein Flügel reicht, um zu gleiten. {Er} übt auf dem Dach, fällt zweimal und steht wieder auf. Unten sieht eine kleine Ratte zu. {N} winkt ihr zu. Du kannst hochkommen, ruft {er}. Aber vorsichtig, die Stufen sind rutschig.'),
    StoryChapter(14, '{G} auf dem Dach', 'Zwei Wochen. Eine kleine Gestalt klettert über die Dachkante und sieht aus, als würde sie gleich umkippen. {N} bietet keinen Rat an. {Er} rückt nur ein Stück zur Seite und schiebt ein Stück Brot hin. Setz dich, sagt {er}. Erzähl, wenn du magst. {G} erzählt. {N} hört zu und merkt, dass das Zuhören auch guttut.'),
    StoryChapter(30, 'Zuhören', 'Ein Monat, und {N} hat entdeckt, was {er} am besten kann: zuhören. {G} erzählt von der Kette, {R} von den Taschen. {Er} sagt wenig, nickt oft und schiebt Brot über die Dachkante. Wer mir einmal zuhört, sagt {er} leise, der hat schon die Hälfte geschafft. Es ist das Wichtigste, was {er} je weitergegeben hat, und es passt in keinen Briefumschlag.'),
    StoryChapter(60, 'Der alte Weg', 'Zwei Monate. {N} fliegt zum ersten Mal wieder die Route, die {er} als Bote geflogen ist. Die Häuser sind dieselben, aber {er} sieht sie anders. In einem Fenster brennt Licht. Dahinter sitzt jemand, der auf Post wartet. {N} landet, klopft und sagt nur: Ich hab nichts für dich, aber ich bleibe kurz. Der Mensch öffnet die Tür.'),
    StoryChapter(90, 'Die Nacht, in der alles schwer war', 'Neunzig Tage, und trotzdem kommt eine Nacht, in der alles zurückkehrt. {N} sitzt am Rand des Daches. Da klopft es: {G}, {P} und {R}, jeder mit einer Decke. Niemand sagt etwas. Sie setzen sich einfach dazu. Im Morgengrauen merkt {N}, dass {er} nicht allein war. Das ist der Unterschied zu früher: Diesmal trägt {er} die Nachricht nicht allein.'),
    StoryChapter(180, 'Der Taubenschlag', 'Ein halbes Jahr. {N} baut einen Taubenschlag, aber keinen für Tauben. Für alle, die einen Platz suchen, einen warmen Raum und jemanden, der zuhört. Über der Tür hängt ein Schild aus Holz: Hier darfst du müde sein. Es kommen mehr, als {er} dachte. {N} kocht Tee, zeigt auf einen Stuhl und sagt: Setz dich. Erzähl mir, wenn du magst.'),
    StoryChapter(365, 'Der letzte Brief', 'Ein Jahr. {N} schreibt den letzten Brief, und diesmal ist es einer an dich selbst. Du hast viel getragen, steht darin, aber du musst nicht mehr alles tragen. Danke, dass du geblieben bist. {Er} faltet das Papier, steckt es in den Flügel und fliegt, mit einem halben Flügel und ganzem Herzen, über die Brücke zum Haus der Freunde. Dort geht gerade die Tür auf.'),
  ],
};

String fillStory(String text, String id, CompanionGender g) {
  final f = g == CompanionGender.female;
  String name(String c) => companionDisplayName(c, g);
  return text
      .replaceAll('{N}', name(id))
      .replaceAll('{G}', name('gitty'))
      .replaceAll('{P}', name('pjotre'))
      .replaceAll('{R}', name('rocco'))
      .replaceAll('{D}', name('dieter'))
      .replaceAll('{er}', f ? 'sie' : 'er')
      .replaceAll('{Er}', f ? 'Sie' : 'Er')
      .replaceAll('{ihm}', f ? 'ihr' : 'ihm')
      .replaceAll('{ihn}', f ? 'sie' : 'ihn')
      .replaceAll('{sein}', f ? 'ihr' : 'sein')
      .replaceAll('{Kleiner}', f ? 'Kleine' : 'Kleiner');
}

List<StoryChapter> chaptersFor(String id, CompanionGender g, int daysClean) {
  final list = companionStories[id] ?? const [];
  return [
    for (final c in list)
      if (daysClean >= c.day)
        StoryChapter(c.day, fillStory(c.title, id, g), fillStory(c.text, id, g)),
  ];
}
